#ifndef SORTER_HARDWARE_CONFIG_H
#define SORTER_HARDWARE_CONFIG_H

/*
 * Central hardware configuration for the garbage sorter.
 *
 * Servos must be powered from an external 5-6 V supply, not from STM32 GPIO.
 * The external servo supply ground must be connected to STM32 GND.
 *
 * The current CubeIDE .ioc only configures USART2 and the NUCLEO LED/button.
 * Keep SORTER_HARDWARE_ENABLED at 0 until CubeIDE has generated the PWM,
 * ultrasonic GPIO, and SPI/TFT peripherals listed below.
 */
#define SORTER_HARDWARE_ENABLED 0

#if SORTER_HARDWARE_ENABLED
#include "main.h"
#endif

/*
 * Leave this at 1 until all TODO handles/pins below match the CubeIDE .ioc.
 * If SORTER_HARDWARE_ENABLED is set to 1 while this is still 1, the build
 * stops with an obvious message instead of failing later in a confusing way.
 */
#define SORTER_HARDWARE_CONFIG_REQUIRES_CUBEIDE_SETUP 1

#if SORTER_HARDWARE_ENABLED && SORTER_HARDWARE_CONFIG_REQUIRES_CUBEIDE_SETUP
#error "Update sorter_hardware_config.h after CubeIDE generates PWM timers, ultrasonic GPIO, and TFT SPI, then set SORTER_HARDWARE_CONFIG_REQUIRES_CUBEIDE_SETUP to 0."
#endif

/* Servo timer/channel mappings.
 * TODO: Replace htim3/htim4 placeholders with the timer handles generated by CubeIDE.
 * Recommended timer setup: PWM mode, 50 Hz period, 1 us timer tick, period 20000.
 */
#if SORTER_HARDWARE_ENABLED
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim4;
#endif

#define DIVERTER_1_SERVO_TIMER_HANDLE htim3
#define DIVERTER_1_SERVO_CHANNEL TIM_CHANNEL_1
#define DIVERTER_2_SERVO_TIMER_HANDLE htim3
#define DIVERTER_2_SERVO_CHANNEL TIM_CHANNEL_2
#define TRAPDOOR_LEFT_SERVO_TIMER_HANDLE htim4
#define TRAPDOOR_LEFT_SERVO_CHANNEL TIM_CHANNEL_1
#define TRAPDOOR_RIGHT_SERVO_TIMER_HANDLE htim4
#define TRAPDOOR_RIGHT_SERVO_CHANNEL TIM_CHANNEL_2

/* Ultrasonic pin mappings.
 * TODO: Replace these GPIO placeholders with final CubeIDE-generated pins.
 * Trigger pins must be GPIO output. Echo pins must be GPIO input.
 */
#define LANDFILL_US_TRIG_PORT GPIOB
#define LANDFILL_US_TRIG_PIN GPIO_PIN_0
#define LANDFILL_US_ECHO_PORT GPIOB
#define LANDFILL_US_ECHO_PIN GPIO_PIN_1

#define COMPOST_US_TRIG_PORT GPIOB
#define COMPOST_US_TRIG_PIN GPIO_PIN_2
#define COMPOST_US_ECHO_PORT GPIOB
#define COMPOST_US_ECHO_PIN GPIO_PIN_10

#define RECYCLING_US_TRIG_PORT GPIOB
#define RECYCLING_US_TRIG_PIN GPIO_PIN_11
#define RECYCLING_US_ECHO_PORT GPIOB
#define RECYCLING_US_ECHO_PIN GPIO_PIN_12

/* TFT SPI mappings.
 * TODO: Replace hspi1 and control pins with final CubeIDE-generated mappings.
 * The display abstraction currently assumes an ILI9341-style SPI TFT, but the
 * controller-specific driver is intentionally isolated in tft_display.c.
 */
#if SORTER_HARDWARE_ENABLED
extern SPI_HandleTypeDef hspi1;
#endif

#define TFT_SPI_HANDLE hspi1
#define TFT_CS_PORT GPIOA
#define TFT_CS_PIN GPIO_PIN_4
#define TFT_DC_PORT GPIOA
#define TFT_DC_PIN GPIO_PIN_6
#define TFT_RST_PORT GPIOA
#define TFT_RST_PIN GPIO_PIN_7
#define TFT_BL_PORT GPIOA
#define TFT_BL_PIN GPIO_PIN_8
#define TFT_BACKLIGHT_USED 1

/* Servo calibration values in microseconds. Start conservatively and adjust
 * after the linkage is installed. Do not use abstract angles in the motion code.
 */
#define SERVO_MIN_PULSE_US 1000U
#define SERVO_CENTER_PULSE_US 1500U
#define SERVO_MAX_PULSE_US 2000U
#define SERVO_PERIOD_US 20000U
#define SERVO_PWM_TIMER_TICKS_PER_US 1U

#define DIVERTER_1_LEFT_US 1000U
#define DIVERTER_1_RIGHT_US 2000U
#define DIVERTER_2_LEFT_US 1000U
#define DIVERTER_2_RIGHT_US 2000U

#define TRAPDOOR_LEFT_CLOSED_US 1000U
#define TRAPDOOR_LEFT_OPEN_US 2000U
#define TRAPDOOR_RIGHT_CLOSED_US 2000U
#define TRAPDOOR_RIGHT_OPEN_US 1000U

#define DIVERTER_SETTLE_MS 600U
#define TRAPDOOR_OPEN_HOLD_MS 900U
#define TRAPDOOR_CLOSE_SETTLE_MS 500U

/* Two-binary-diverter route table. Edit these macros instead of changing
 * sorter_hardware.c when breadboard wiring or linkage direction changes.
 */
#define LANDFILL_DIVERTER_1_US DIVERTER_1_LEFT_US
#define LANDFILL_DIVERTER_2_US DIVERTER_2_LEFT_US
#define RECYCLING_DIVERTER_1_US DIVERTER_1_RIGHT_US
#define RECYCLING_DIVERTER_2_US DIVERTER_2_LEFT_US
#define COMPOST_DIVERTER_1_US DIVERTER_1_RIGHT_US
#define COMPOST_DIVERTER_2_US DIVERTER_2_RIGHT_US

/* Ultrasonic calibration values. If distance to trash surface is below the
 * threshold, that bin is considered almost full. Sorting is not blocked yet.
 */
#define ULTRASONIC_TIMEOUT_US 30000U
#define BIN_ALMOST_FULL_DISTANCE_CM 8.0f

#endif /* SORTER_HARDWARE_CONFIG_H */
