from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
TRAIN_DIR = DATA_DIR / "train"
VAL_DIR = DATA_DIR / "val"
TEST_DIR = DATA_DIR / "test"

MODELS_DIR = PROJECT_ROOT / "models"
LOGS_DIR = PROJECT_ROOT / "logs"

MODEL_PATH = MODELS_DIR / "garbage_classifier.pt"
PREDICTIONS_LOG_PATH = LOGS_DIR / "predictions.csv"

CLASS_NAMES = ["landfill", "compost", "recycling"]
SPLITS = ["train", "val", "test"]

IMAGE_SIZE = 224
BATCH_SIZE = 16
LEARNING_RATE = 0.0001
NUM_EPOCHS = 10
CONFIDENCE_THRESHOLD = 0.80

WEBCAM_ROI_WIDTH_RATIO = 0.55
WEBCAM_ROI_HEIGHT_RATIO = 0.55
BACKGROUND_CALIBRATION_FRAMES = 45
BACKGROUND_LEARNING_RATE = 0.02
OBJECT_PRESENT_AREA_RATIO = 0.08
OBJECT_STABLE_FRAMES = 12
OBJECT_CLEAR_FRAMES = 18
FOREGROUND_THRESHOLD = 35

SUPPORTED_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]
